services:
  web:
    build: .
#    command: uv run ./manage.py runserver 0.0.0.0:8000
    command: /start.sh
    mem_limit: 200m
    deploy:
      resources:
        limits:
          memory: 200M
    ports:
      - "8011:8000"
    env_file:
      - .env
    volumes:
      - ./:/app
      - ./.ipython:/root/.ipython/profile_default
    depends_on:
      - db
      - redis
    image: 'web'

  bot:
    image: 'web'
    command: bash -c 'uv run python -m bot.main'
    mem_limit: 200m
    deploy:
      resources:
        limits:
          memory: 200M
    env_file:
      - .env
    volumes:
      - ./:/app
    depends_on:
      - db
      - redis

  db:
      image: postgres:latest
      mem_limit: 300m
      deploy:
        resources:
          limits:
            memory: 300M
      expose:
        - 5432
      env_file:
        - .env
      volumes:
        - postgres_data:/var/lib/postgresql/data/

  redis:
    image: docker.io/redis:6
    mem_limit: 100m
    deploy:
      resources:
        limits:
          memory: 100M

    volumes:
      - redis_data:/data

volumes:
  postgres_data:
  redis_data:
